import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for AI book content
  aiBookSidebar: [
    'ai_book/week1-2-introduction-physical-ai',
    'ai_book/module1_ros2',
    'ai_book/module2_digital_twin',
    'ai_book/module3_ai_brain',
    'ai_book/module4_vla',
  ],
};

export default sidebars;
